version: '3'
services:
  resource-backend:
    image: "resource_api:0.0.4"
    environment:
      - SPRING.PROFILES.ACTIVE=default, in-memory

  resource-frontend:
    image: "resource_ui:0.0.5"
    ports:
      - "3000:3000"
      
  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
